### ISSUE TITLE
Pagination (angular)

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper-backbone#59]
Right now all results are being displayed, but pagination needs to be implemented like in the current susper 
![image](https://cloud.githubusercontent.com/assets/20185076/22067511/91a7006c-ddb7-11e6-9e81-375a9cab8b3a.png)
Can be done once #58 is merged

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 looks like you have fixed it ,close this issue and follow up for the next improvements at https://github.com/fossasia/susper.com rather than here .
